# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
