# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_verified',
            field=models.BooleanField(default=False),
        ),
    ]
