# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20170717_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
